### ISSUE TITLE
Feature: light mode and palette variations

### ISSUE THREAD

**Issue by mirrordoll** [dotzenith/lovesay.rs#1]
Hello! I think lovesay is really cute, however I think it would be better if it were able to give the colorschemes a light mode version. Maybe something like [theme]-light values for the LOVESAY_COLORSCHEME env variable.

(The terminal theme is Gruvbox Light Hard)
![image](https://github.com/dotzenith/lovesay.rs/assets/135416052/d42b361b-4620-4da7-8fa0-394e37af0102)

It would also be pretty cool if there was a way to customize each heart's color :3 Thanks by the way

**Comment by dotzenith** [comment]
Hi! Thank you for the feedback :) I think light mode colors make a lot of sense and I'm sure there are other users who would appreciate them. 

The colors in lovesay are dependent on [kolorz](https://github.com/dotzenith/kolorz.rs). It's a really simple library, so if you'd like to add Gruvbox Light Hard to lovesay, feel free to open a PR on the [kolorz](https://github.com/dotzenith/kolorz.rs) repo and I'll be sure to take a look.

As for different color for each heart, I think that would be difficult to add without significant code change and I'd like to keep lovesay simple.

**Comment by dotzenith** [comment]
Closing as completed in release [0.5.4](https://github.com/dotzenith/lovesay.rs/releases/tag/0.5.4)
